default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: pw

development:
  <<: *default
  database: cross
  host: 127.0.0.1

test:
  <<: *default
  database: cross_test
  host: 127.0.0.1

production:
  <<: *default
  database: cross
  password: <%= ENV['CROSS_DATABASE_PASSWORD'] %>
